# Generated by Django 4.0.3 on 2024-02-19 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_categoery', '0001_initial'),
        ('available_skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sub_categoery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('desc', models.TextField()),
                ('job_categoery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_categoery.jobcategory')),
                ('skills_accuired', models.ManyToManyField(to='available_skills.availableskill')),
                ('sub_categoery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_categoery.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
