# Generated by Django 4.0.3 on 2024-07-03 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('TemplateID', models.AutoField(primary_key=True, serialize=False)),
                ('TemplateName', models.CharField(max_length=100)),
                ('TemplateSubject', models.CharField(max_length=255)),
                ('template_body_before', models.TextField()),
                ('template_body_after', models.TextField()),
                ('Status', models.CharField(default='Active', max_length=10)),
                ('CreatedDateTime', models.DateTimeField(auto_now_add=True)),
                ('LastUpdatedDateTime', models.DateTimeField(auto_now=True)),
                ('CCTO', models.EmailField(blank=True, max_length=254, null=True)),
                ('signatures', models.CharField(max_length=200)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
