# Generated by Django 4.0.3 on 2024-07-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=225)),
                ('location', models.CharField(max_length=225)),
                ('brand_email', models.EmailField(max_length=254)),
                ('service', models.CharField(max_length=225)),
            ],
        ),
    ]
