# Generated by Django 4.0.3 on 2024-03-13 11:22

from django.db import migrations, models
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[employee.models.validate_date_of_birth]),
        ),
        migrations.AlterField(
            model_name='employeeuser',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True, validators=[employee.models.validate_date_of_joning]),
        ),
        migrations.AlterField(
            model_name='employeeuser',
            name='role',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='employeeuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Intern', 'Intern'), ('Employee', 'Employee'), ('Senior Employee', 'Senior Employee'), ('CEO', 'CEO'), ('Teacher', 'Teacher')], max_length=225, null=True),
        ),
    ]
