# Generated by Django 4.0.3 on 2024-03-13 11:16

from django.db import migrations, models
import employee.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=225, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=225)),
                ('phone', models.IntegerField(unique=True)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField(validators=[employee.models.validate_date_of_birth])),
                ('date_of_joining', models.DateField(validators=[employee.models.validate_date_of_joning])),
                ('role', models.CharField(max_length=225)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('user_type', models.CharField(choices=[('Intern', 'Intern'), ('Employee', 'Employee'), ('Senior Employee', 'Senior Employee'), ('CEO', 'CEO'), ('Teacher', 'Teacher')], max_length=225)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
