# Generated by Django 4.0.3 on 2024-03-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employeeuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeuser',
            name='phone',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
