# Generated by Django 4.0.3 on 2024-07-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenu',
            name='label',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='link',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
