# Generated by Django 4.0.3 on 2024-02-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internuser',
            name='intern_name',
            field=models.CharField(default='Simply 2 Cloud', max_length=300),
        ),
    ]
