# Generated by Django 4.0.3 on 2024-03-26 05:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendence_tracer', '0003_alter_attendence_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendence',
            unique_together={('employee_user', 'date')},
        ),
    ]
