# Generated by Django 4.0.3 on 2024-07-17 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentattendence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='leave_reason',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='notes',
        ),
    ]
