# Generated by Django 4.0.3 on 2024-07-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0004_alter_batchmodel_batch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchmodel',
            name='batch_name',
            field=models.CharField(max_length=200),
        ),
    ]
