# Generated by Django 4.0.3 on 2024-05-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='unread_message_count',
            field=models.IntegerField(default=1),
        ),
    ]
