# Generated by Django 4.0.3 on 2024-08-10 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batch', '0005_alter_batchmodel_batch_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('signature', models.TextField()),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batch.batchmodel')),
            ],
        ),
    ]
