# Generated by Django 4.0.3 on 2024-07-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailtemplate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='signature',
            field=models.TextField(),
        ),
    ]
