# Generated by Django 4.0.3 on 2024-02-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('Web Devlopment', 'Web Devlopment'), ('App Devlopment', 'App Devlopment'), ('MERN Stack', 'MERN Stack'), ('Graphic Designer', 'Graphic Designer'), ('Video Editor', 'Video Editor')], max_length=225)),
            ],
        ),
    ]
