# Generated by Django 4.0.3 on 2024-07-04 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('countrycode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcountrycode',
            name='company_id',
            field=models.ForeignKey(default=1, limit_choices_to={'company_admin': True}, on_delete=django.db.models.deletion.CASCADE, related_name='company_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
