# Generated by Django 4.0.3 on 2024-03-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence_tracer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='check_in_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='date',
            field=models.DateField(auto_now_add=True, unique=True),
        ),
    ]
