# Generated by Django 4.0.3 on 2024-03-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence_tracer', '0002_alter_attendence_check_in_time_alter_attendence_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
