# Generated by Django 4.0.3 on 2024-07-03 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emailtemplate', '0001_initial'),
        ('companycustomer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRouteSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date_time', models.DateTimeField()),
                ('schedule_route_id', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('schedule', 'Schedule'), ('sent', 'Sent')], default='schedule', max_length=250)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('schedule_customer', models.ManyToManyField(to='companycustomer.customer')),
                ('schedule_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailtemplate.emailtemplate')),
            ],
        ),
    ]
