# Generated by Django 4.0.3 on 2024-07-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0002_alter_batchmodel_batch_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
