# Generated by Django 4.0.3 on 2024-07-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0003_alter_batchmodel_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchmodel',
            name='batch_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
