# Generated by Django 4.0.3 on 2024-07-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=300, unique=True)),
                ('subject', models.CharField(max_length=300)),
                ('template_body', models.TextField()),
                ('signature', models.CharField(max_length=500)),
            ],
        ),
    ]
