# Generated by Django 4.0.3 on 2024-08-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailtemplate', '0002_alter_emailtemplate_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
