# Generated by Django 4.0.3 on 2024-02-13 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('available_skills', '0001_initial'),
        ('skills', '0002_skill_skill_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='available_skills.availableskill'),
        ),
    ]
