# Generated by Django 4.0.3 on 2024-07-05 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companycustomer', '0003_alter_customer_company_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpAdderessCompanyCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('active', models.BooleanField(default=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companycustomer.customer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ipadderesscompanycustomer',
            constraint=models.UniqueConstraint(fields=('company_id', 'ip_address'), name='unique_ip_addresses'),
        ),
    ]
