# Generated by Django 4.0.3 on 2024-04-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('half_day', 'Half Day'), ('full_day', 'Full Day')], max_length=250, null=True),
        ),
    ]
