# Generated by Django 4.0.3 on 2024-02-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_alter_skill_skill_id'),
        ('available_skills', '0001_initial'),
        ('intern_profile_job', '0002_internjobprofile_available_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internjobprofile',
            name='available_skills',
            field=models.ManyToManyField(null=True, to='available_skills.availableskill'),
        ),
        migrations.AlterField(
            model_name='internjobprofile',
            name='skills',
            field=models.ManyToManyField(null=True, to='skills.skill'),
        ),
    ]
