# Generated by Django 4.0.3 on 2024-03-22 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern_profile_job', '0006_alter_internjobprofile_sub_categoery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internjobprofile',
            name='expected_salary',
        ),
        migrations.RemoveField(
            model_name='internjobprofile',
            name='github_profile',
        ),
        migrations.RemoveField(
            model_name='internjobprofile',
            name='title',
        ),
    ]
