# Generated by Django 4.0.3 on 2024-05-21 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern_profile_job', '0010_internjobprofile_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internjobprofile',
            old_name='education',
            new_name='experience',
        ),
    ]
