# Generated by Django 4.0.3 on 2024-07-13 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_phone', models.IntegerField()),
                ('student_email', models.EmailField(max_length=254)),
                ('active', models.BooleanField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=200)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_added_by', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assigned_to', to=settings.AUTH_USER_MODEL)),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batch.batchmodel')),
            ],
        ),
    ]
