# Generated by Django 4.0.3 on 2024-07-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='assigned_to',
        ),
        migrations.AlterField(
            model_name='student',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
