# Generated by Django 4.0.3 on 2024-02-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSlugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title_slug', models.CharField(blank=True, max_length=5000, null=True, unique=True)),
                ('location_slug', models.CharField(blank=True, max_length=5000, null=True, unique=True)),
                ('company_name_slug', models.CharField(blank=True, max_length=5000, null=True, unique=True)),
            ],
        ),
    ]
