# Generated by Django 4.0.3 on 2024-02-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_alter_skill_skill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='job_profiles/'),
        ),
    ]
