# Generated by Django 4.0.3 on 2024-02-13 07:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sub_categoery', '0001_initial'),
        ('job_categoery', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternJobProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('expected_salary', models.IntegerField(validators=[django.core.validators.MinValueValidator(5000, message='Expected salary must be at least 3000.'), django.core.validators.MaxValueValidator(100000, message='Expected salary must not exceed 1 lakh.')])),
                ('experience_years', models.IntegerField()),
                ('desc', models.TextField()),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job_categoery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_categoery.jobcategory')),
                ('skills', models.ManyToManyField(blank=True, null=True, to='skills.skill')),
                ('sub_categoery', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sub_categoery.subcategory')),
            ],
        ),
    ]
