# Generated by Django 4.0.3 on 2024-02-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_alter_skill_skill_id'),
        ('available_skills', '0001_initial'),
        ('intern_profile_job', '0004_internjobprofile_github_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internjobprofile',
            name='available_skills',
            field=models.ManyToManyField(blank=True, to='available_skills.availableskill'),
        ),
        migrations.AlterField(
            model_name='internjobprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='skills.skill'),
        ),
    ]
