# Generated by Django 4.0.3 on 2024-04-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_profile_job', '0007_remove_internjobprofile_expected_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internjobprofile',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='job_profiles/'),
        ),
    ]
