# Generated by Django 4.0.3 on 2024-04-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_profile_job', '0008_internjobprofile_thumbnail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='internjobprofile',
            name='short_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
